#!/bin/bash

name=discordovercri

git pull
container_id=$(sudo docker container ls | grep "$name" | cut -d' ' -f1)
if ! [ -z "$container_id" ]; then
	sudo docker container stop $container_id
fi
sudo docker image rm --force "$name"
sudo docker build -t "$name" .
# sudo docker run -d $(pwd):/app "$name"
# sudo docker run -d -v db_"$name":/app "$name"
sudo docker run -it -v db_"$name":/app/db "$name" /bin/bash
