#!/bin/bash

name=discordovercri

git pull
container_id=$(sudo docker container ls | grep "$name" | cut -d' ' -f1)
if ! [ -z "$container_id" ]; then
	sudo docker container stop $container_id
fi
sudo docker image rm --force "$name"
sudo docker build --no-cache -t "$name" .
sudo docker run -d -v db_"$name"1:/app/db -v db_"$name"2:/app/assets/ "$name"
# sudo docker run -it -v db_"$name"1:/app/db/ -v db_"$name"2:/app/assets/ "$name" /bin/bash
